import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(projectRoot, "node_modules", "js-yaml", "dist", "js-yaml.min.js");
const targetDir = path.join(projectRoot, "inject", "vendor", "js-yaml");
const targetPath = path.join(targetDir, "js-yaml.shim.js");

function ensureSourceExists() {
  if (!fs.existsSync(sourcePath)) {
    throw new Error(
      "js-yaml source not found at " + sourcePath + ". Run `npm install` in the extension directory first."
    );
  }
}

function buildShim(minSource) {
  return (
    "/**\n" +
    " * Vendored js-yaml for page-world injection (CJS shim avoids AMD collision).\n" +
    " * Generated by scripts/vendor-js-yaml.js — do not edit manually.\n" +
    " */\n" +
    "(function ccpJsYamlVendorShim() {\n" +
    "  var module = { exports: {} };\n" +
    "  var exports = module.exports;\n" +
    minSource +
    "\n" +
    "  var CCP = (window.__CCP__ = window.__CCP__ || {});\n" +
    "  CCP.__jsyaml = module.exports;\n" +
    "})();\n"
  );
}

function run() {
  ensureSourceExists();
  fs.mkdirSync(targetDir, { recursive: true });
  const minSource = fs.readFileSync(sourcePath, "utf8");
  fs.writeFileSync(targetPath, buildShim(minSource), "utf8");
  const sizeKb = Math.round(fs.statSync(targetPath).size / 1024);
  console.log("[vendor-js-yaml] wrote", path.relative(projectRoot, targetPath), "(" + sizeKb + " KB)");
}

run();
